### ISSUE TITLE
Sharedmobility POI not shown in DemoApp

### ISSUE THREAD

**Issue by u233336** [openTdataCH/ojp-sdk#48] opened 2024-06-11 11:23 UTC

**Comment by u233336** [comment] 2024-06-11 11:26
All the objects from the API from the "Bundesamt für ENergie" are not shown on the Demo App (but they are used in the routing)

**Comment by vasile** [comment] 2024-06-11 20:50
Hi @TO-mdv please have a look at the following POI BBOX LIR request for OJP v1
```
/POST https://api.opentransportdata.swiss/ojp2020
```
https://gist.github.com/vasile/94f223257aa4da2a9aca2657e45133a3

- the number of results exceeds the given limit (300)
- the BBOX (which is from BE bahnhof area) is not respected, i.e. results from whole Switzerland are shown
- other requests filter types (i.e. `stop` or `POI.service`) are working fine

You can visualize the request/response here
https://tools.odpch.ch/ojp-api-explorer/lir?gist=94f223257aa4da2a9aca2657e45133a3

<img width="1361" alt="image" src="https://github.com/openTdataCH/ojp-sdk/assets/113994/d0c5b81b-033f-4826-958f-e59034cba2a1">

**Comment by vasile** [comment] 2024-07-02 13:58
@TO-mdv the issue seems to be fixed - cant reproduce it anymore, you can safely ignore
@u233336 - the patch for PROD is deployed, closing

<img width="775" alt="image" src="https://github.com/openTdataCH/ojp-sdk/assets/113994/59f6279f-fef0-4348-8835-f05d1b4ce657">

**Closed as completed by vasile** 2024-07-02 13:58 UTC
