### ISSUE TITLE
LIR "Ba" + Type=stop return no entries

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#8] opened 2024-04-20 22:07 UTC
https://tools.odpch.ch/ojp-api-explorer-v2/?gist=55350e671acfddff976e8c6c54306b3b

Expected are `Baden`, `Basel SBB`, etc

```
<OJP xmlns:siri="http://www.siri.org.uk/siri" xmlns="http://www.vdv.de/ojp" version="2.0">
  <OJPResponse>
    <siri:ServiceDelivery>
      <siri:ResponseTimestamp>2024-04-20T22:14:19.7657336+00:00</siri:ResponseTimestamp>
      <siri:ProducerRef>MENTZ</siri:ProducerRef>
      <OJPLocationInformationDelivery>
        <siri:ResponseTimestamp>2024-04-20T22:14:19.7657383+00:00</siri:ResponseTimestamp>
        <siri:RequestMessageRef>677460f9-50cb-45f9-bcf5-a1524e32444a</siri:RequestMessageRef>
        <siri:DefaultLanguage>de</siri:DefaultLanguage>
        <CalcTime>3</CalcTime>
      </OJPLocationInformationDelivery>
    </siri:ServiceDelivery>
  </OJPResponse>
</OJP>
```

Request
`/POST https://api.opentransportdata.swiss/ojp20`
XML: https://gist.github.com/vasile/55350e671acfddff976e8c6c54306b3b

**Comment by AndreasAtSBB** [comment] 2024-04-30 11:26
Just checked what reference is showing bls.ch:
![image](https://github.com/openTdataCH/ojp-sdk/assets/85744651/f5a1e9d5-fd3f-4383-a3ba-daa0c5eb721d)
Nothing!

Probably we should try then to use with 3 letters:
![image](https://github.com/openTdataCH/ojp-sdk/assets/85744651/f206d694-e1e8-466a-bef3-74e511d2669c)
I think that's an acceptable result!

**Comment by TO-mdv** [comment] 2024-05-15 08:17
Search should also work for 2 letters. It works without restriction, but as soon a filter like stop or address is set, it's not working anymore. We will fix that:  [SH-2931](https://youtrack.mentz.net/issue/SH-2931) OJP2.0 LIR liefert keine Ergebnisse für "Ba" -> LIR-1g_SP_LocationName_Stop mit 2 Buchstaben

**Comment by TO-mdv** [comment] 2024-05-23 13:05
@vasile also here, is there really a Usecase to search by 2 letters and you expect the object you are looking for? There are too many results for stops and address as well.
sbb.ch gives you a response, but they are not really useful in my opinion:


![Image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/6c5b02e9-1e78-4d16-ac81-1753bd46f58c)


So I would propose to close this issue and expect the use to enter more details.

**Comment by vasile** [comment] 2024-05-23 14:38
Cant the system use a different smaller index search for 2-letter search terms? I.e. top stops in Switzerland.
If we exclude then also people travelling to `Au` (ZH or SG) will be affected ;)

**Comment by TO-mdv** [comment] 2024-05-23 17:45
The problem isn't the 2-letter search, in some cirumstances also a 2-letter search works, example "au":
1. Aarau STOP
2. Aurec STOP
3. Autun STOP
4. Aubiat STOP
5. Auboué STOP
6. Auggen STOP
7. Altnau STOP
8. Auxonne STOP
9. Au ZH STOP
10. Au SG STOP

The problem is effective with search strings that would return too many results, like it is for "ba".

**Comment by vasile** [comment] 2024-05-24 12:57
Hi @TO-mdv , happy with `wontfix` for now but would be nice if we can revisit later on. Closing

**Comment by vasile** [comment] 2024-05-24 13:57
For future analyse, BLS Mobile (Hafas backend) is returning meaningful results, lets park it somewhere else

<img width="300" src="https://github.com/openTdataCH/ojp-sdk/assets/113994/cbf40066-c1c0-4667-a219-4407360268c8"/>

**Comment by vasile** [comment] 2024-05-24 14:36
Closing again the actual issue - opened #37 for further discussions on 2-letter search queries

**Closed** 2024-05-24 14:36 UTC
Labels: search-quality, prioHIGH, blocker
